package lambdas;

// FUNÇÕES LAMBDAS SÃO FUNÇÕES ANÔNIMAS QUE UTILIZAMOS DENTRO DO CÓDIGO
// PARA DEFINIR QUE UMA INTERFACE RECEBA UMA FUNÇÃO LAMBDA A INTERFACE PRECISA TER A NOMENCLATURA/ANNOTATION ABAIXO
@FunctionalInterface
// ESSA ANNONTATION/NOMENCLATURA VALIDA QUE VOCÊ SÓ UTILIZE UM MÉTODO/FUNÇÃO NESSA INTERFACE
public interface Calculo {
	public abstract double executar(double a, double b);
}